version: '3.8'

services: 
  server:
    container_name: server
    build: 
      context: ./server
    depends_on:
      - postgres
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
      - /server/node_modules

  postgres:  
    container_name: postgres
    restart: "always"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:14.4
